# ComfyUI配置
comfyui:
  # ComfyUI服务端口
  port: 8188
  # ComfyUI输出目录
  output_dir: "E:\\ComfyUI\\ComfyUI\\output"

text_to_image:
  ckpt_name: realisticVisionV60B1_v51HyperVAE.safetensors  # 你实际有的模型名
  sampler_name: euler
  scheduler: normal
  default_width: 512
  default_height: 512
  default_steps: 20
  default_cfg_scale: 7.0

image_to_video:
  model_name: realisticVisionV60B1_v51HyperVAE.safetensors
  default_fps: 8
  default_duration: 5.0
  default_motion_strength: 0.8 