# ComfyUI配置
comfyui:
  # ComfyUI服务端口
  port: 8188
  # ComfyUI输出目录
  output_dir: "E:\\ComfyUI\\ComfyUI\\output"

# 全局默认配置
defaults:
  # 通用图像生成参数
  image:
    default_width: 936
    default_height: 1664
    default_steps: 28
    default_cfg_scale: 3.9
    default_sampler: "dpmpp_2m"
    default_scheduler: "sgm uniform"
    supported_aspect_ratios: ["1:1", "9:16", "16:9"]
  
  # 通用视频生成参数
  video:
    default_fps: 8
    default_duration: 5.0
    default_motion_strength: 0.8

# 模型配置
models:
  # 默认模型配置
  default:
    checkpoint: "Wanxiang XLSuper RealisticV8.4_V8.4.safetensors"
    vae: "auto"  # 使用模型自带的VAE
  
  # 特定任务模型配置
  text_to_image:
    checkpoint: "Wanxiang XLSuper RealisticV8.4_V8.4.safetensors"
    vae: "auto"
  
  image_to_video:
    checkpoint: "Wanxiang XLSuper RealisticV8.4_V8.4.safetensors"
    vae: "auto"

# 工作流配置
workflows:
  # 默认工作流
  default_workflow: "标准文生图"
  
  # 工作流类别
  categories:
    text_to_image: ["标准文生图"]
    image_to_video: ["万相2.1图生视频"]
  
  # 工作流特定配置（覆盖全局默认值）
  settings:
    "标准文生图":
      width: 936
      height: 1664
      steps: 28
      cfg_scale: 3.9
      sampler: "dpmpp_2m"
      scheduler: "sgm uniform"
    
    "万相2.1图生视频":
      duration: 5.0
      fps: 8
      motion_strength: 0.8

# MySQL数据库配置
mysql:
  host: localhost
  port: 3306
  user: root                    # 请修改为你的MySQL用户名
  password: "123456"               # 请修改为你的MySQL密码
  database: comfyui_admin       # 数据库名称 