# 多模态内容生成工作流管理系统配置
server:
  host: 192.168.110.91
  port: 8000
version: "1.0"

# ComfyUI配置 (兼容性保留，用于单机模式)
comfyui:
  host: "127.0.0.1"
  port: 8188
  output_dir: "outputs"
  timeout: 300  # 请求超时时间（秒）

# 分布式配置
distributed:
  enabled: true  # 启用分布式模式

  # 文件管理配置
  file_management:
    proxy_output_dir: "outputs/distributed"  # 主机代理输出目录
    enable_file_cache: true                  # 启用文件缓存
    cache_ttl: 3600                         # 缓存过期时间(秒)
    max_cache_size: "1GB"                   # 最大缓存大小

  # 节点同步配置
  sync:
    enable_file_sync: false  # 是否启用文件同步到主机
    sync_interval: 300       # 同步间隔(秒)
    sync_patterns:           # 同步文件模式
      - "*.png"
      - "*.jpg"
      - "*.mp4"
      - "*.gif"

# 分布式节点配置
nodes:
  # 节点发现模式: static(静态配置) | dynamic(动态发现) | hybrid(混合模式)
  discovery_mode: "static"

  # 健康检查配置
  health_check:
    interval: 30  # 健康检查间隔(秒)
    timeout: 5    # 健康检查超时(秒)
    heartbeat_timeout: 60  # 心跳超时(秒)
    retry_attempts: 3      # 重试次数

  # 负载均衡配置
  load_balancing:
    strategy: "least_loaded"  # round_robin | least_loaded | weighted | random
    enable_failover: true     # 启用故障转移
    max_retries: 3           # 最大重试次数

  # 静态节点配置 - 配置从机节点
  static_nodes:
    # 从机节点1 - 请修改为实际的从机IP地址
    - node_id: "comfyui-worker-1"
      host: "192.168.111.6"  # TODO: 修改为实际的从机IP地址
      port: 8188
      max_concurrent: 4
      capabilities: ["text_to_image", "image_to_video"]  # 支持的任务类型
      metadata:
        location: "worker-server-1"
        gpu_model: "RTX 4090"
        priority: 1
        description: "主要工作节点"

    # 从机节点2 - 可扩展配置 (可选)
    # - node_id: "comfyui-worker-2"
    #   host: "192.168.1.102"  # TODO: 修改为实际的从机IP地址
    #   port: 8188
    #   max_concurrent: 2
    #   capabilities: ["text_to_image"]
    #   metadata:
    #     location: "worker-server-2"
    #     gpu_model: "RTX 3080"
    #     priority: 2
    #     description: "备用工作节点"

  # 动态发现配置 (预留)
  dynamic_discovery:
    enabled: false
    broadcast_port: 8189
    discovery_interval: 60

# Redis配置（任务队列）
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null

# MySQL数据库配置（三数据库架构）
mysql:
  # 客户端数据库配置
  client:
    host: localhost
    port: 3306
    user: root
    password: "123456"
    database: comfyui_client
    charset: utf8mb4
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600

  # 管理后台数据库配置
  admin:
    host: localhost
    port: 3306
    user: root
    password: "123456"
    database: comfyui_admin
    charset: utf8mb4
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  # 共享数据库配置
  shared:
    host: localhost
    port: 3306
    user: root
    password: "123456"
    database: comfyui_shared
    charset: utf8mb4
    pool_size: 15
    max_overflow: 30
    pool_timeout: 30
    pool_recycle: 3600

# 任务类型配置
task_types:
  # 文生图任务
  text_to_image:
    enabled: true
    default_workflow: "sd_basic"
    max_concurrent_tasks: 4
    priority: 1
    workflows:
      sd_basic:
        name: "Stable Diffusion Basic"
        version: "1.0"
        workflow_file: "workflows/text_to_image/文生图.json"
        description: "基础文生图工作流"

        # 参数映射配置 - 精确定义每个参数在工作流中的位置
        parameter_mapping:
          # 1. 模型参数 - 节点4的CheckpointLoaderSimple
          checkpoint:
            node_id: "4"
            input_name: "ckpt_name"
            default_value: "SD\\realisticVisionV60B1_v51HyperVAE.safetensors"
            data_type: "string"
            description: "模型文件路径"

          # 2. 图片分辨率和批次 - 节点135的EmptySDXLLatentImage
          width:
            node_id: "135"
            input_name: "width"
            default_value: 512
            data_type: "int"
            description: "图片宽度"

          height:
            node_id: "135"
            input_name: "height"
            default_value: 512
            data_type: "int"
            description: "图片高度"

          batch_size:
            node_id: "135"
            input_name: "batch_size"
            default_value: 4
            data_type: "int"
            description: "批次数量"

          # 3. 正向提示词 - 节点314的GoogleTranslateTextNode
          prompt:
            node_id: "314"
            input_name: "text"
            default_value: ""
            data_type: "string"
            description: "正向提示词"

          # 4. 反向提示词 - 节点317的AutoNegativePrompt
          negative_prompt:
            node_id: "317"
            input_name: "base_negative"
            default_value: "text, watermark"
            data_type: "string"
            description: "反向提示词"

          # 5. 种子参数 - 节点294的KSampler
          seed:
            node_id: "294"
            input_name: "seed"
            default_value: -1
            data_type: "int"
            description: "随机种子，-1表示随机生成"

        # 前端允许提交的参数白名单
        allowed_frontend_params:
          - checkpoint
          - width
          - height
          - batch_size
          - seed
          - prompt
          - negative_prompt

      sdxl_basic:
        name: "SDXL Basic"
        version: "1.0"
        workflow_file: "workflows/text_to_image/SDXL-文生图.json"
        description: "SDXL基础文生图工作流，支持更高分辨率"

        # 参数映射配置 - 精确定义每个参数在SDXL工作流中的位置
        parameter_mapping:
          # 1. 模型参数 - 节点4的CheckpointLoaderSimple
          checkpoint:
            node_id: "4"
            input_name: "ckpt_name"
            default_value: "SDXL\\juggernautXL_juggXIByRundiffusion_2.safetensors"
            data_type: "string"
            description: "SDXL模型文件路径"

          # 2. 图片分辨率和批次 - 节点5的EmptyLatentImage
          width:
            node_id: "5"
            input_name: "width"
            default_value: 832
            data_type: "int"
            description: "图片宽度"

          height:
            node_id: "5"
            input_name: "height"
            default_value: 1480
            data_type: "int"
            description: "图片高度"

          batch_size:
            node_id: "5"
            input_name: "batch_size"
            default_value: 1
            data_type: "int"
            description: "批次数量"

          # 3. 正向提示词 - 节点79的GoogleTranslateTextNode
          prompt:
            node_id: "79"
            input_name: "text"
            default_value: ""
            data_type: "string"
            description: "正向提示词"

          # 4. 反向提示词 - 节点78的AutoNegativePrompt
          negative_prompt:
            node_id: "78"
            input_name: "base_negative"
            default_value: "text"
            data_type: "string"
            description: "反向提示词"

          # 5. 种子参数 - 节点10的KSamplerAdvanced (BASE)
          seed:
            node_id: "10"
            input_name: "noise_seed"
            default_value: -1
            data_type: "int"
            description: "随机种子，-1表示随机生成"

        # 前端允许提交的参数白名单
        allowed_frontend_params:
          - checkpoint
          - width
          - height
          - batch_size
          - seed
          - prompt
          - negative_prompt

  # 图生视频任务
  image_to_video:
    enabled: true
    default_workflow: "Wan2.1 i2v"
    max_concurrent_tasks: 2
    priority: 2
    workflows:
      "Wan2.1 i2v":
        name: "Wan2.1 Image2Video"
        version: "1.0"
        workflow_file: "workflows/image_to_video/Wan2.1 图生视频.json"
        description: "Wan2.1 --- 万相通义开源视频模型"

        # 参数映射配置 - 精确定义每个参数在工作流中的位置
        parameter_mapping:
          # 1. 正向提示词 - 节点55的Insert Positive Prompt
          prompt:
            node_id: "55"
            input_name: "text"
            default_value: ""
            data_type: "string"
            description: "正向提示词"

          # 2. 反向提示词 - 节点59的Insert Negative Prompt
          negative_prompt:
            node_id: "59"
            input_name: "text"
            default_value: "text, watermark"
            data_type: "string"
            description: "反向提示词"

          # 3. 加载图片 - 节点54的LoadImage
          image:
            node_id: "54"
            input_name: "image"
            default_value: ""
            data_type: "string"
            description: "加载图片路径"

        # 前端允许提交的参数白名单
        allowed_frontend_params:
          - prompt
          - negative_prompt
          - image

# 参数处理策略配置
parameter_strategies:
  merge_strategy: "smart_merge"  # frontend_priority, config_priority, smart_merge, conditional
  validation_mode: "strict"     # strict, lenient, disabled
  type_conversion: true         # 自动类型转换

# 任务队列配置
task_queue:
  broker_url: "redis://localhost:6379/0"
  result_backend: "redis://localhost:6379/0"
  task_serializer: "json"
  result_serializer: "json"
  accept_content: ["json"]
  timezone: "UTC"
  enable_utc: true
  task_routes:
    "app.queue.tasks.execute_text_to_image_task": {"queue": "text_to_image"}
    "app.queue.tasks.execute_image_to_video_task": {"queue": "image_to_video"}
    "app.queue.tasks.execute_generic_workflow_task": {"queue": "celery"}
  worker_prefetch_multiplier: 1
  task_acks_late: true
  worker_max_tasks_per_child: 100

# 系统配置
system:
  max_file_size: 50  # MB
  allowed_image_formats: ["jpg", "jpeg", "png", "webp"]
  cleanup_interval: 3600  # 清理间隔（秒）
  task_retention_time: 86400  # 任务保留时间（秒）