# Python 日志配置文件
# 用于 FastAPI 和其他 Python 服务

version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: /app/logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: /app/logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  celery_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/logs/celery.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  # 根日志器
  '':
    level: INFO
    handlers: [console, file]
    propagate: false
  
  # FastAPI 相关
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  fastapi:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  # 应用日志器
  app:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  
  app.core:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  app.api:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  app.database:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  app.queue:
    level: INFO
    handlers: [console, celery_file]
    propagate: false
  
  # Celery 日志器
  celery:
    level: INFO
    handlers: [console, celery_file]
    propagate: false
  
  celery.task:
    level: INFO
    handlers: [console, celery_file]
    propagate: false
  
  celery.worker:
    level: INFO
    handlers: [console, celery_file]
    propagate: false
  
  # 数据库日志器
  sqlalchemy:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  sqlalchemy.engine:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  # Redis 日志器
  redis:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  # HTTP 客户端日志器
  requests:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  aiohttp:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  # 第三方库日志器
  PIL:
    level: WARNING
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
